spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: username
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:sql/init.sql
      data-locations: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none
