INSERT INTO dbo.COIN_CHINESE_CONVERSION VALUES (NEXT VALUE FOR dbo.HIBERNATE_SEQUENCE, 'USD', '美金');
INSERT INTO dbo.COIN_CHINESE_CONVERSION VALUES (NEXT VALUE FOR dbo.HIBERNATE_SEQUENCE, 'GBP', '英鎊');
INSERT INTO dbo.COIN_CHINESE_CONVERSION VALUES (NEXT VALUE FOR dbo.HIBERNATE_SEQUENCE, 'EUR', '歐元');