DROP SCHEMA IF EXISTS dbo;
CREATE SCHEMA dbo;
USE dbo;
CREATE TABLE IF NOT EXISTS COIN_CHINESE_CONVERSION
(
    ID      INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODE    VARCHAR (100) NOT NULL UNIQUE,
    CHINESE VARCHAR (100) NOT NULL
);

CREATE SEQUENCE dbo.HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;